

```{r}
library(tidyverse)
happiness_data <- read.csv("/Users/rellamas/math_and_algos/R/final/2022.csv")
```
```{r}
# remove empty "xx" country remove dataframe
happiness_data <- happiness_data[-c(147), ]
```

```{r}
install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", 
"ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))
```
```{r}
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```



```{r}
# cleaning

# remove 3 unused columns from happiness df
drops <- c("Whisker.high", "Whisker.low", "Dystopia..1.83....residual")
happiness_data <- happiness_data[ , !(names(happiness_data) %in% drops)]

# remove all instances of '*' from happiness df 'happiness score' column
happiness_data$Country <- as.character(gsub("\\*","", happiness_data$Country))  # regex


# convert chr to doubles
# 1
happiness_data$Happiness.score <- as.numeric(gsub(",","", happiness_data$Happiness.score))
# 2
happiness_data$Explained.by..GDP.per.capita <- as.numeric(gsub(",","", happiness_data$Explained.by..GDP.per.capita))
# 3
happiness_data$Explained.by..Social.support <- as.numeric(gsub(",","", happiness_data$Explained.by..Social.support))
# 4
happiness_data$Explained.by..Healthy.life.expectancy <- as.numeric(gsub(",","", happiness_data$Explained.by..Healthy.life.expectancy))
# 5
happiness_data$Explained.by..Freedom.to.make.life.choices <- as.numeric(gsub(",","", happiness_data$Explained.by..Freedom.to.make.life.choices))
# 6
happiness_data$Explained.by..Generosity <- as.numeric(gsub(",","", happiness_data$Explained.by..Generosity))
# 7 
happiness_data$Explained.by..Perceptions.of.corruption <- as.numeric(gsub(",","", happiness_data$Explained.by..Perceptions.of.corruption))
```


```{r}
# gdp per capita
attach(happiness_data)
ggplot(data = happiness_data, 
       aes(Explained.by..GDP.per.capita, Happiness.score)) +
  geom_point() +
  geom_smooth(method = lm) +
  xlab("GDP per Capita") +
  ylab("Happiness") +
  ggtitle("Happiness vs. GDP per Capita")

gdp_res <- lm(Explained.by..GDP.per.capita ~ Happiness.score, data = happiness_data)
summary(gdp_res)
# p-value: < 2.2e-16
# beta 1: 0.29628
# Adjusted R-squared:  0.5803 
```

```{r}
# social support
attach(happiness_data)
ggplot(data = happiness_data, 
       aes(Explained.by..Social.support, Happiness.score)) +
  geom_point() +
  geom_smooth(method = lm) +
  xlab("Social Support") +
  ylab("Happiness") +
  ggtitle("Happiness vs. Social Support")

social_support_res <- lm(Explained.by..Social.support ~ Happiness.score, data = happiness_data)
summary(social_support_res)
# p-value: < 2.2e-16
# beta 1: 0.2005
# Adjusted R-squared:  0.6024 
```

```{r}
# healthy life expectancy
attach(happiness_data)
ggplot(data = happiness_data, 
       aes(Explained.by..Healthy.life.expectancy, Happiness.score)) +
  geom_point() +
  geom_smooth(method = lm)  +
  xlab("Healthy Life Expectancy") +
  ylab("Happiness") +
  ggtitle("Happiness vs. Healthy Life Expectancy")

life_expectancy_res <- lm(Explained.by..Healthy.life.expectancy ~ Happiness.score, data = happiness_data)
summary(life_expectancy_res)
# p-value: < 2e-16
# beta 1: 0.12011
# Adjusted R-squared:  0.5448 
```

```{r}
# freedom to make life choices
attach(happiness_data)
ggplot(data = happiness_data, 
       aes(Explained.by..Freedom.to.make.life.choices, Happiness.score)) +
  geom_point() +
  geom_smooth(method = lm) +
  xlab("Freedom to Make Life Choices") +
  ylab("Happiness") +
  ggtitle("Happiness vs. Freedom to Make Life Choices")

freedom_res <- lm(Explained.by..Freedom.to.make.life.choices ~ Happiness.score, data = happiness_data)
summary(freedom_res)
# p-value: < 2e-16
# beta 1: 0.083854
# Adjusted R-squared:  0.3862 
```

```{r}
# generosity
attach(happiness_data)
ggplot(data = happiness_data, 
       aes(Explained.by..Generosity, Happiness.score)) +
  geom_point() +
  geom_smooth(method = lm) +
  xlab("Generosity") +
  ylab("Happiness") +
  ggtitle("Happiness vs. Generosity")

generosity_res <- lm(Explained.by..Generosity ~ Happiness.score, data = happiness_data)
summary(generosity_res)
# p-value: 0.4444
# beta 1: 4.859e-03
# Adjusted R-squared:  -0.002848 
```

```{r}
# perception of corruption
attach(happiness_data)
ggplot(data = happiness_data, 
       aes(Explained.by..Perceptions.of.corruption, Happiness.score)) +
  geom_point() +
  geom_smooth(method = lm) +
  xlab("Perception of Corruption") +
  ylab("Happiness") +
  ggtitle("Happiness vs. Perception of Corruption") +
  theme_economist()

corruption_res <- lm(Explained.by..Perceptions.of.corruption ~ Happiness.score, data = happiness_data)
summary(corruption_res)
# p-value: 1.74e-07
# beta 1: 0.04883
# Adjusted R-squared:  0.1675 
# qqnorm(resid(corruption_res))
# qqline(resid(corruption_res))
```


```{r}


```

```{r}
# combining happiness, connectedness, and loneliness into one dataframe
#     will have to remove 4 countries
df2 <- merge(connected, lonely, by="Country")
df <- merge(happiness_data, df2)
# remove all instances of '*' from happiness df 'happiness score' column
df$Very.Fairly.x <- as.numeric(gsub("\\%","", df$Very.Fairly.x))  # regex
df$Very.Fairly.y <- as.numeric(gsub("\\%","", df$Very.Fairly.y))  # regex

ggplot(data = df, 
       aes(Very.Fairly.x, Happiness.score)) +
  geom_point() +
  geom_smooth(method = lm) +
  xlab("Connected") +
  ylab("Happiness") +
  ggtitle("Very Connected vs. Happiness")

ggplot(data = df, 
       aes(Very.Fairly.y, Happiness.score)) +
  geom_point() +
  geom_smooth(method = lm) +
  xlab("Lonely") +
  ylab("Happiness") +
  ggtitle("Very Lonely vs. Happiness")
```

