---
title: "spy"
author: "jrellamas"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(glue)
```

```{r}
buy_close_strat <- function(historical) {
  browser()
  for (i in 1:length(historical[[1]])) {
    
  }
}
```


```{r}
# SPY <- read.csv("/Users/rellamas/math_and_algos/SPY/SPY.csv")
# SPY <- read.csv("/Users/rellamas/math_and_algos/SPY/SOXX.csv")
SPY <- read.csv("/Users/rellamas/math_and_algos/SPY/SOXL.csv")
SPY[SPY == "null"] = NA
SPY <- na.omit(SPY)

SPY$Open <- as.double(SPY$Open)
SPY$High <- as.double(SPY$High)
SPY$Low <- as.double(SPY$Low)
SPY$Close <- as.double(SPY$Close)
SPY$Adj.Close <- as.double(SPY$Adj.Close)
SPY$Volume <- as.integer(SPY$Volume)


old <- SPY$Open[1]
new <- SPY$Close[length(SPY[[1]])]
p_change_normal <- ( new - old ) / old
glue('3Y % Change: {p_change_normal}')
overnight_vect <- c()
overnight_percent_change_vect <- c()
for (i in 1:length(SPY[[1]])) {
  close <- SPY$Close[i]
  next_open <- SPY$Open[i + 1]
  if (!is.na(next_open)) {
    overnight <- next_open - close
    night_percent <- (next_open - close) / close
    overnight_vect <- c(overnight_vect, overnight)
    overnight_percent_change_vect <- c(overnight_percent_change_vect, night_percent)
  }
  # print(glue('Close: {close}, Next Open: {next_open}'))
}

# calculate overnight strat return of spy
overnight_return <- 1
for (i in overnight_percent_change_vect) {
  if (i < 0) {
    overnight_return <- overnight_return * (1 - i)
  } else {
    overnight_return <- overnight_return * (1 + i)
  }
}
overnight_return <- overnight_return * .01
glue('Overnight Strat: {overnight_return}')
dif <- overnight_return - p_change_normal
glue('Percent Difference Between Overnight Strat vs Buy & Hold: {dif}')
```

